version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-alpha1
    container_name: esmaster1
    environment:
      - node.name=esmaster1
      - cluster.initial_master_nodes=esmaster1,esmaster2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-alpha1
    container_name: esmaster2
    environment:
      - node.name=esmaster2
      - discovery.seed_hosts=esmaster1
      - cluster.initial_master_nodes=esmaster1,esmaster2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
